#!/bin/sh
export PATH=$HOME/.cabal/bin:$HOME/.bin:$PATH
export STARTUP=$HOME/.cabal/bin/xmonad

xset -b &
xsetroot -cursor_name left_ptr &
setxkbmap -layout us,cz_qwerty -option grp:alt_shift_toggle &
xcompmgr &

# Generated randr command with arandr
.screenlayout/default.sh
nitrogen --restore &

urxvtd -q -o -f &
pamusb-agent &

trayer --monitor primary --edge bottom --align right \
       --SetDockType true --SetPartialStrut true \
       --expand true --widthtype percent --width 5 \
       --transparent true --alpha 0 --tint 0x002b36 \
       --height 18 &

nm-applet &
claws-mail &
ssh-add &

# Requires Debian's Xsession script with Xsession.d batteries included...
/etc/X11/Xsession
